on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
name: Bump stage branch
jobs:
  bump-stage:
    name: 'Bump stage branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER }}
        run: |
          git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Git merge from main
        run: |
          git fetch --no-tags origin main
          git merge origin/main --no-squash -m 'chore: bumped stage branch from main'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: bumped stage branch from main'
          title: '[chore] Bump stage branch from main'
          branch: chore/bump-stage
          delete-branch: true
          body: >
            PR to bump stage branch.
          labels: chore, automated pr
